In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

## 1.회원정보_train_컬럼추출

In [3]:
# 1. 모든 parquet 파일 경로 가져오기
file_list = glob.glob('open/train/1.회원정보/2018*_train_회원정보.parquet')

# 2. 데이터프레임 리스트 생성
df_list = [pd.read_parquet(f) for f in file_list]

# 3. 하나로 합치기
all_df = pd.concat(df_list, ignore_index=True)

# 4. 확인
print(all_df.shape)
all_df.head(10)

(2400000, 78)

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15
5,201807,TRAIN_000005,2,30대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),51
6,201807,TRAIN_000006,1,20대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,독신,6
7,201807,TRAIN_000007,2,60대,E,1,1,1,1,2,...,0,0,0,0개,0개,0개,0개,0,노년생활,28
8,201807,TRAIN_000008,1,30대,C,1,1,1,1,3,...,0,0,0,0개,0개,0개,0개,1,자녀출산기,5
9,201807,TRAIN_000009,1,20대,E,1,0,0,1,1,...,0,0,0,0개,0개,0개,0개,0,독신,10

### 원하는 컬럼만 추출

In [5]:
# 원하는 컬럼들 선택
selected_columns = [
    '기준년월',
    'ID',
    '이용가능여부_해외겸용_본인',
    '보유여부_해외겸용_본인',
    '수신거부여부_TM',
    '수신거부여부_메일',
    '수신거부여부_DM',
    '이용금액_R3M_신용체크',
    '이용금액_R3M_신용',
    '_1순위카드이용금액',
    '이용카드수_신용체크',
    '_2순위카드이용금액',
    '_1순위카드이용건수',
    '_2순위카드이용건수',
    '이용카드수_신용', 
]

# 해당 컬럼만 추출하여 새로운 데이터프레임 생성
filtered_df = all_df[selected_columns]

# 결과 확인
print(filtered_df.head())

     기준년월            ID  이용가능여부_해외겸용_본인  보유여부_해외겸용_본인  수신거부여부_TM  수신거부여부_메일  \
0  201807  TRAIN_000000               0             0          0          0
1  201807  TRAIN_000001               0             0          0          0
2  201807  TRAIN_000002               1             1          0          0
3  201807  TRAIN_000003               1             1          0          0
4  201807  TRAIN_000004               1             1          0          0

   수신거부여부_DM  이용금액_R3M_신용체크  이용금액_R3M_신용  _1순위카드이용금액  이용카드수_신용체크  _2순위카드이용금액  \
0          0            196          196        3681           1           0
1          0          13475        13475       13323           1           0
2          0          23988        23988       24493           1           0
3          0           3904         3904        5933           1           0
4          0           1190            0           0           1           0

   _1순위카드이용건수  _2순위카드이용건수  이용카드수_신용
0          26           0         1
1          46           0         1
2          28           0         1
3           1           0         1
4          -2           0         0

In [6]:
print(filtered_df.tail())

           기준년월            ID  이용가능여부_해외겸용_본인  보유여부_해외겸용_본인  수신거부여부_TM  \
2399995  201812  TRAIN_399995               1             1          0
2399996  201812  TRAIN_399996               1             1          0
2399997  201812  TRAIN_399997               1             1          1
2399998  201812  TRAIN_399998               0             0          1
2399999  201812  TRAIN_399999               0             0          1

         수신거부여부_메일  수신거부여부_DM  이용금액_R3M_신용체크  이용금액_R3M_신용  _1순위카드이용금액  \
2399995          0          0          10755         7267        5640
2399996          0          0          27636        27636       26357
2399997          1          1          23187        23187       17171
2399998          1          1              0            0           0
2399999          1          1          21463        21463        6984

         이용카드수_신용체크  _2순위카드이용금액  _1순위카드이용건수  _2순위카드이용건수  이용카드수_신용
2399995           1           0           3           0         0
2399996           1           0          38           0         1
2399997           1           0          33           0         1
2399998           0           0          -2           0         0
2399999           2       14564          -2          52         2

In [7]:
# # CSV 파일로 저장
# filtered_df.to_csv('open/data/1.회원정보_train_filtered_data.csv', index=False, encoding='utf-8')

In [8]:
# # parquet 파일로 저장
# filtered_df.to_parquet('open/data/1.회원정보_train_filtered_data.parquet', index=False)

## 1.회원정보_test_컬럼추출

In [10]:
# 1. 모든 parquet 파일 경로 가져오기
file_list_test = glob.glob('open/test/1.회원정보/2018*_test_회원정보.parquet')

# 2. 데이터프레임 리스트 생성
df_list_test = [pd.read_parquet(f) for f in file_list_test]

# 3. 하나로 합치기
all_df_test = pd.concat(df_list_test, ignore_index=True)

# 4. 확인
print(all_df_test.shape)
all_df_test.head(10)

(600000, 77)

,기준년월,ID,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TEST_00000,1,40대,1,1,0,1,2,2,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),45
1,201807,TEST_00001,1,60대,1,1,0,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀독립기,19
2,201807,TEST_00002,1,40대,1,1,1,1,2,2,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),5
3,201807,TEST_00003,2,40대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),7
4,201807,TEST_00004,2,40대,1,0,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),1
5,201807,TEST_00005,2,30대,0,0,0,1,1,0,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),19
6,201807,TEST_00006,1,30대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,가족구축기,24
7,201807,TEST_00007,1,50대,1,1,1,1,2,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),3
8,201807,TEST_00008,1,40대,1,0,0,1,2,2,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),19
9,201807,TEST_00009,2,40대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),23

In [11]:
# 원하는 컬럼들 선택
selected_columns = [
    '기준년월',
    'ID'
    '이용가능여부_해외겸용_본인',
    '보유여부_해외겸용_본인',
    '수신거부여부_TM',
    '수신거부여부_메일',
    '수신거부여부_DM',
    '이용금액_R3M_신용체크',
    '이용금액_R3M_신용',
    '_1순위카드이용금액',
    '이용카드수_신용체크',
    '_2순위카드이용금액',
    '_1순위카드이용건수',
    '_2순위카드이용건수',
    '이용카드수_신용', 
]

# 해당 컬럼만 추출하여 새로운 데이터프레임 생성
filtered_df_test = all_df_test[selected_columns]

# 결과 확인
print(filtered_df_test.head())

     기준년월          ID  소지카드수_이용가능_신용  소지카드수_유효_신용  이용가능여부_해외겸용_본인  \
0  201807  TEST_00000              2            2               1
1  201807  TEST_00001              1            1               1
2  201807  TEST_00002              2            2               0
3  201807  TEST_00003              1            1               1
4  201807  TEST_00004              1            1               1

   보유여부_해외겸용_본인  수신거부여부_TM  수신거부여부_메일  수신거부여부_DM  이용금액_R3M_신용체크  이용금액_R3M_신용  \
0             1          1          1          1          21458        21458
1             1          0          0          0          18681        10759
2             0          0          0          0          40758        40758
3             1          0          0          0           5255         5255
4             1          1          1          1          16148        14290

   _1순위카드이용금액  이용카드수_신용체크  _2순위카드이용금액  _1순위카드이용건수  _2순위카드이용건수  이용카드수_신용
0       13852           2        6021          51          33         2
1       11065           2           0          40           0         1
2       27071           2       10704         154          69         2
3        4827           1           0         105           0         1
4        8011           3        6387          52          39         2

In [12]:
# # CSV 파일로 저장
# filtered_df.to_csv('open/data/1.회원정보_test_filtered_data.csv', index=False, encoding='utf-8')

In [13]:
# parquet 파일로 저장
filtered_df_test.to_parquet('open/data/1.회원정보_test_filtered_data.parquet', index=False)